### PR TITLE
Add support for MPI function `wtime`

### PR DESCRIPTION
**Pull request by xann16**

### CODE REVIEW

**Comment by slayoo** [comment]
@xann16 this sounds exciting!
we're apparently missing the new source files in this branch, though:
image

**Comment by xann16** [comment]
Sadly that is not a mistake. Yet, anyhow.

The codebase is totally changed since last time I've contributed, so I wanted to make sure everything works fine and to make sure I can depend on CI/CD chacks during development.

I'm trying to add features required for my experiments with rewriting turbulence code and tis is the first step, I can't assure when and whether it will succeed, but if I get stuck, I'll let You know. Another step would be to try to add some limited functionaity from `fftw` (either based on `mpi4py-fft` or `pyFFTW` packages, but this is another can of worms for later.

When I get to something concrete here I'll change PR status from Draft and request Your review. I hope it won't take forever ;)

**Comment by slayoo** [comment]
Thanks @xann16 !!!
I've pushed some cosmetic changes to the tests (just aiming at having one assert per test).

Concerning isort and other pre-commig warnings, you can make it run automatically locally before each commit by doing `pre-commit install` or on-demand by using `pre-commit run --all-files`

**Review by slayoo — APPROVED** [review]

**Comment by slayoo** [comment]
and I suggest merging now - to make small incremental changes and releasing as often as possible - please confirm if OK?

**Comment by xann16** [comment]
Gladly @slayoo 

I hoped to do this all in one go but my time turned out to be more limited this weekend. Not to mention that it took me some time to reacquaint with CI infrastructure, etc. Thanks for all the tips.

You can freely merge (o I can do it) - BTW: it would ba a great idea here to squash it to a single commit as I made a bit of mess here. Do You support such option? I cannot see it on merge button dropdown....

**Comment by slayoo** [comment]
@xann16, great!
In the repo setting, we disabled all but squash-merging, so it is done by default for all PRs without offering other options.
Big thanks! Merging and releasing!

**Pull request merged**
